add_test([=[algo.midpoint]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=algo.midpoint]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[algo.midpoint]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[algo.below]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=algo.below]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[algo.below]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[algo.between]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=algo.between]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[algo.between]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[algo.intersect]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=algo.intersect]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[algo.intersect]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[algo.developOld]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=algo.developOld]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[algo.developOld]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[algo.develop]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=algo.develop]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[algo.develop]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[algo.intersectp]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=algo.intersectp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[algo.intersectp]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[modulo.basic]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=modulo.basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[modulo.basic]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[alloc.basic]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=alloc.basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[alloc.basic]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[alloc.vt]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=alloc.vt]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[alloc.vt]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[bio.vsum]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=bio.vsum]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[bio.vsum]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[bio.specOp]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=bio.specOp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[bio.specOp]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[bio.physio]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=bio.physio]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[bio.physio]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[boost.lcm]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=boost.lcm]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[boost.lcm]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[boost.tribool]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=boost.tribool]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[boost.tribool]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[chrono.hms]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=chrono.hms]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[chrono.hms]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[clipper.largenum]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=clipper.largenum]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[clipper.largenum]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[clipper.small]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=clipper.small]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[clipper.small]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[clipper.request]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=clipper.request]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[clipper.request]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[clipper.miss]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=clipper.miss]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[clipper.miss]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[clipper.size]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=clipper.size]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[clipper.size]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[clipper.example]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=clipper.example]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[clipper.example]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[clipper.m85a]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=clipper.m85a]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[clipper.m85a]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[clipper.m85b]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=clipper.m85b]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[clipper.m85b]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[clipper.dual]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=clipper.dual]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[clipper.dual]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[distance.basic]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=distance.basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[distance.basic]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[frontier.example2D]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=frontier.example2D]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[frontier.example2D]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[frontier.direct]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=frontier.direct]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[frontier.direct]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[frontier.level]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=frontier.level]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[frontier.level]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[frontier.repro]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=frontier.repro]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[frontier.repro]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[frontier.obj]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=frontier.obj]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[frontier.obj]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[frontier.propagate]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=frontier.propagate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[frontier.propagate]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[frontier.store]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=frontier.store]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[frontier.store]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[expression.constant]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=expression.constant]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[expression.constant]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[expression.base]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=expression.base]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[expression.base]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[expression.construct]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=expression.construct]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[expression.construct]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[expression.parse]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=expression.parse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[expression.parse]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[expression.solo]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=expression.solo]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[expression.solo]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[sexpression.ops]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=sexpression.ops]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[sexpression.ops]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[sexpression.base]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=sexpression.base]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[sexpression.base]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[sexpression.badsize]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=sexpression.badsize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[sexpression.badsize]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[sexpression.xvel]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=sexpression.xvel]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[sexpression.xvel]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[sexpression.cse]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=sexpression.cse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[sexpression.cse]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcellxml.errorPrint]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcellxml.errorPrint]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcellxml.errorPrint]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[boundary.circle]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=boundary.circle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[boundary.circle]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[boundary.expanding]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=boundary.expanding]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[boundary.expanding]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[trait.basic]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=trait.basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[trait.basic]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.create]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.create]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.create]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.compound]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.compound]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.compound]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.slab]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.slab]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.slab]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.slabExtend]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.slabExtend]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.slabExtend]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.extendCompound]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.extendCompound]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.extendCompound]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.static3D]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.static3D]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.static3D]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.compoundArray]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.compoundArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.compoundArray]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.compoundWithVar]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.compoundWithVar]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.compoundWithVar]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.variableArray]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.variableArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.variableArray]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.vcellHelper]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.vcellHelper]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.vcellHelper]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.bugDemo]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.bugDemo]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.bugDemo]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[hdf5.flex3]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=hdf5.flex3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[hdf5.flex3]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[inside.insideSquare]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=inside.insideSquare]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[inside.insideSquare]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[inside.diamond]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=inside.diamond]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[inside.diamond]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[inside.diamondcache]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=inside.diamondcache]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[inside.diamondcache]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[inside.insideTriangle]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=inside.insideTriangle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[inside.insideTriangle]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[inside.sp1]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=inside.sp1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[inside.sp1]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[inside.sp2]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=inside.sp2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[inside.sp2]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[logger.macro]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=logger.macro]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[logger.macro]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[logger.key]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=logger.key]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[logger.key]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[logger.level]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=logger.level]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[logger.level]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[logger.exception]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=logger.exception]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[logger.exception]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[logger.position]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=logger.position]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[logger.position]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[loopiter.basic]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=loopiter.basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[loopiter.basic]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.mesNeighbor]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.mesNeighbor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.mesNeighbor]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.mes]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.mes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.mes]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.mesh]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.mesh]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.mesh]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.dogx]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.dogx]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.dogx]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.speciesSpecification]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.speciesSpecification]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.speciesSpecification]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.movingBoundarySetup]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.movingBoundarySetup]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.movingBoundarySetup]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.movingBoundaryProblem]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.movingBoundaryProblem]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.movingBoundaryProblem]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.prim]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.prim]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.prim]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.string]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.string]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.string]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.stringVector]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.stringVector]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.stringVector]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.TPoint]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.TPoint]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.TPoint]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.arrays]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.arrays]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.arrays]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.TPointVector]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.TPointVector]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.TPointVector]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.MPoint]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.MPoint]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.MPoint]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.MeshDef]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.MeshDef]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.MeshDef]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.volume]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.volume]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.volume]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.segment]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.segment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.segment]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.doubleRegister]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.doubleRegister]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.doubleRegister]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.vector]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.vector]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.vector]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.offset]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.offset]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.offset]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.circle]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.circle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.circle]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.world]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.world]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.world]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.npc]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.npc]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.npc]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[persist.complexVolume]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=persist.complexVolume]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[persist.complexVolume]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[mes.states]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=mes.states]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[mes.states]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[mbs.lifetime]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=mbs.lifetime]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[mbs.lifetime]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[memory.vector]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=memory.vector]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[memory.vector]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcell_util.convert]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcell_util.convert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcell_util.convert]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcell_util.valid]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcell_util.valid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcell_util.valid]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[segment.construct]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=segment.construct]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[segment.construct]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[segment.equal]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=segment.equal]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[segment.equal]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[segment.lessthan]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=segment.lessthan]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[segment.lessthan]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[segment.assign]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=segment.assign]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[segment.assign]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[segment.sort]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=segment.sort]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[segment.sort]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[segment.taxicab]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=segment.taxicab]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[segment.taxicab]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[segment.singular]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=segment.singular]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[segment.singular]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[segment.magnitude]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=segment.magnitude]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[segment.magnitude]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[segment.output]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=segment.output]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[segment.output]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[segment.handv]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=segment.handv]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[segment.handv]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcellutil.digits]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcellutil.digits]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcellutil.digits]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcellutil.multiply]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcellutil.multiply]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcellutil.multiply]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcellutil.vcarray]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcellutil.vcarray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcellutil.vcarray]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcellutil.print]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcellutil.print]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcellutil.print]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcellutil.nochange]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcellutil.nochange]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcellutil.nochange]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcellutil.dictionary]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcellutil.dictionary]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcellutil.dictionary]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcellutil.teebuf]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcellutil.teebuf]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcellutil.teebuf]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcellutil.spy1]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcellutil.spy1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcellutil.spy1]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vcellutil.spy]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vcellutil.spy]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vcellutil.spy]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[voronoi.basic]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=voronoi.basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[voronoi.basic]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[voronoi.particular]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=voronoi.particular]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[voronoi.particular]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[voronoi.threerow]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=voronoi.threerow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[voronoi.threerow]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[voronoi.timing]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=voronoi.timing]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[voronoi.timing]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[angle.basic]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=angle.basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[angle.basic]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[angle.range]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=angle.range]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[angle.range]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[angle.leftRight]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=angle.leftRight]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[angle.leftRight]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vector.print]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vector.print]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vector.print]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vectortest.basic]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vectortest.basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vectortest.basic]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vectortest.dot]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vectortest.dot]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vectortest.dot]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vectortest.perpendicular]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vectortest.perpendicular]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vectortest.perpendicular]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[vectortest.angle]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=vectortest.angle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[vectortest.angle]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[highv.buildi]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=highv.buildi]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[highv.buildi]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[volume.polygons]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=volume.polygons]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[volume.polygons]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[volume.multipoly]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=volume.multipoly]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[volume.multipoly]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[volume.polyaccessor]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=volume.polyaccessor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[volume.polyaccessor]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[volume.persistpoly]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=volume.persistpoly]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[volume.persistpoly]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[volume.randpoly]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=volume.randpoly]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[volume.randpoly]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[volume.intersections]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=volume.intersections]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[volume.intersections]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[volume.swaptest]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=volume.swaptest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[volume.swaptest]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[volume.persist]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=volume.persist]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[volume.persist]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[array.exists]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=array.exists]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[array.exists]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[universe.basic]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=universe.basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[universe.basic]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[universe.doubleinit]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=universe.doubleinit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[universe.doubleinit]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[universe.badvalues]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=universe.badvalues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[universe.badvalues]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[universe.cvt3]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=universe.cvt3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[universe.cvt3]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[universe.cvt1]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=universe.cvt1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[universe.cvt1]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[universe.cvt2]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=universe.cvt2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[universe.cvt2]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[universe.diag]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=universe.diag]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[universe.diag]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[universe.intervals]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=universe.intervals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[universe.intervals]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[universe.herror]=]  /home/cbontempi/projects/vcell-solvers/bin/TestMovingBoundary [==[--gtest_filter=universe.herror]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[universe.herror]=]  PROPERTIES WORKING_DIRECTORY /home/cbontempi/projects/vcell-solvers/MBSolver/Tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  TestMovingBoundary_TESTS algo.midpoint algo.below algo.between algo.intersect algo.developOld algo.develop algo.intersectp modulo.basic alloc.basic alloc.vt bio.vsum bio.specOp bio.physio boost.lcm boost.tribool chrono.hms clipper.largenum clipper.small clipper.request clipper.miss clipper.size clipper.example clipper.m85a clipper.m85b clipper.dual distance.basic frontier.example2D frontier.direct frontier.level frontier.repro frontier.obj frontier.propagate frontier.store expression.constant expression.base expression.construct expression.parse expression.solo sexpression.ops sexpression.base sexpression.badsize sexpression.xvel sexpression.cse vcellxml.errorPrint boundary.circle boundary.expanding trait.basic hdf5.create hdf5.compound hdf5.slab hdf5.slabExtend hdf5.extendCompound hdf5.static3D hdf5.compoundArray hdf5.compoundWithVar hdf5.variableArray hdf5.vcellHelper hdf5.bugDemo hdf5.flex3 inside.insideSquare inside.diamond inside.diamondcache inside.insideTriangle inside.sp1 inside.sp2 logger.macro logger.key logger.level logger.exception logger.position loopiter.basic persist.mesNeighbor persist.mes persist.mesh persist.dogx persist.speciesSpecification persist.movingBoundarySetup persist.movingBoundaryProblem persist.prim persist.string persist.stringVector persist.TPoint persist.arrays persist.TPointVector persist.MPoint persist.MeshDef persist.volume persist.segment persist.doubleRegister persist.vector persist.offset persist.circle persist.world persist.npc persist.complexVolume mes.states mbs.lifetime memory.vector vcell_util.convert vcell_util.valid segment.construct segment.equal segment.lessthan segment.assign segment.sort segment.taxicab segment.singular segment.magnitude segment.output segment.handv vcellutil.digits vcellutil.multiply vcellutil.vcarray vcellutil.print vcellutil.nochange vcellutil.dictionary vcellutil.teebuf vcellutil.spy1 vcellutil.spy voronoi.basic voronoi.particular voronoi.threerow voronoi.timing angle.basic angle.range angle.leftRight vector.print vectortest.basic vectortest.dot vectortest.perpendicular vectortest.angle highv.buildi volume.polygons volume.multipoly volume.polyaccessor volume.persistpoly volume.randpoly volume.intersections volume.swaptest volume.persist array.exists universe.basic universe.doubleinit universe.badvalues universe.cvt3 universe.cvt1 universe.cvt2 universe.diag universe.intervals universe.herror)
